### ISSUE TITLE
Add option to include reader button in URL bar

### ISSUE THREAD

**Issue by Ascrod** [Ascrod/readerview#16]
Use an about:config option to toggle between fixed and free locations.

**Comment by aaferrari** [comment]
[Master Password+](https://addons.mozilla.org/firefox/addon/master-password/) allows you to do that with this configuration dialog:
![Master Password+ display options](https://user-images.githubusercontent.com/1002969/34474616-15b99aa8-ef60-11e7-87bb-c285edd00dfd.png)
The extension works well in Pale Moon (at least for the basic use that I give it) so perhaps this functionality could be implemented in Reader View without major problems.
Another extension with a similar configuration is [UnPlug](https://addons.mozilla.org/es/firefox/addon/unplug/) (so that it can work correctly it must be installed with [Moon Tester Tool](http://addons.palemoon.org/addon/moon-tester-tool/)).

**Comment by Ascrod** [comment]
Thanks for the tip. I will be referencing the existing Reader UI code in FF ESR/Basilisk for this issue, but it never hurts to have other examples as well.

**Comment by Ascrod** [comment]
Should be resolved with 2d11a9ac3d46fe1001032cca5b11b96e15003227.
