### ISSUE TITLE
Interferes with the local Pale Moon Start Page

### ISSUE THREAD

**Issue by kasutajaimin** [Ascrod/readerview#23]
Buttons, enter on input stop working, search provider's logo disappears.
(Double checked with only Tab Groups enabled)

But many thanks for the port! Really missed it.

**Comment by waig3000** [comment]
The initial page search (about:home) d'not work when readerview is ative.

**Comment by Ascrod** [comment]
Thanks for the report, and apologies for not getting to it sooner. I can confirm that the add-on does indeed break the search feature and the buttons. What's interesting is that it isn't supposed to do anything with a page unless it's http or https. It may have something to do with the code that initializes and updates the button.

**Comment by Ascrod** [comment]
It's as I suspected. The declaration of the tab progress listener here:
https://github.com/Ascrod/readerview/blob/a1630fbe7c674453770613c236ccf640d884ba04/chrome/content/readerMain.js#L40
Seems to overwrite a variable with the same name in [Pale Moon's browser.js](https://github.com/MoonchildProductions/Pale-Moon/blob/master/browser/base/content/browser.js#L4103). I'm actually surprised this didn't break a lot more stuff. I'll move those "floating" declarations into the AboutReaderListener scope so that it won't be possible for any of that code to stomp on something else in the future.

I should be able to get a fix out for this in the next release.

**Comment by kasutajaimin** [comment]
Great!
And absolutely no need to apologize. I'm grateful for any activity at all around Pale Moon, to anyone sparing their valuable time :bow:

**Comment by Ascrod** [comment]
Not a problem. :) Working on this add-on is (usually) more enjoyable than not, and I'm glad that people besides myself find it useful.

This issue should now be resolved with da0dab32128662ef70c81ae7390c48760cdae73c.
